### ISSUE TITLE
ReplaceAll is not a function error

### ISSUE THREAD

**Issue by rajacs50** [mdn/sprints#3328]
# Request type
- [x] Correction or update

# Details
The document page that explains string.replaceAll throws an error when you run the demo setup. When I google the error many stackoverflow posts mention that it is not a valid function. Any clarification on this would be much appreciated.

[ReplaceAll MDN Page.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)

![image](https://user-images.githubusercontent.com/56812923/83516585-fce40980-a4f4-11ea-85c4-6e3eca7ea3aa.png)

**Comment by Elchi3** [comment]
Hey @rajacs50, replaceAll is relatively new. What browser version are you using? Please check the compat table: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#Browser_compatibility

**Comment by rajacs50** [comment]
Thank you @Elchi3 I was on FF 76, and after updating to 77 it worked now. I jumped the gun without checking the supported version table! Apologies.
